
GET http://localhost:3000/todos/?status=TO%20DO
###
GET http://localhost:3000/todos/?priority=HIGH
###
GET http://localhost:3000/todos/?priority=HIGH&status=IN%20PROGRESS
###
GET http://localhost:3000/todos/?search_q=Play
###
GET http://localhost:3000/todos/2/
###
POST http://localhost:3000/todos/
{
  "id": 10,
  "todo": "Finalize event theme",
  "priority": "LOW",
  "status": "TO DO"
}
###
PUT http://localhost:3000/todos/3/
{
  "status": "DONE"
}
###
PUT http://localhost:3000/todos/3/
{
  "priority": "HIGH"
}
###
PUT  http://localhost:3000/todos/1/
{
  "todo": "Some task"
}
###
DELETE http://localhost:3000/todos/1/